
clean:
	make -C cdd_temp clean
	make -C char_memory clean
	make -C devicefile_auto clean
	make -C dynamic_cdd clean
	make -C multiple_cdd -i clean
	make -C register_chrdev clean
	make -C kernel_panic clean

