all: thread1 thread2 thread3 thread3a thread4 thread5 thread6 thread6a thread7 thread8 thread8a
#all: thread1 thread2 
#CFLAGS=-D_REENTRANT
#LDFLAGS=-lpthread

thread1: 
	gcc thread1.c -o thread1 -lpthread
thread2: 
	gcc thread2.c -o thread2 -lpthread
thread3: 
	gcc thread3.c -o thread3 -lpthread
thread3a: 
	gcc thread3a.c -o thread3a -lpthread
thread4: 
	gcc thread4.c -o thread4 -lpthread
thread5: 
	gcc thread5.c -o thread5 -lpthread
thread6: 
	gcc thread6.c -o thread6 -lpthread
thread6a: 
	gcc thread6a.c -o thread6a -lpthread
thread7: 
	gcc thread7.c -o thread7 -lpthread
thread8: 
	gcc thread8.c -o thread8 -lpthread
thread8a: 
	gcc thread8a.c -o thread8a -lpthread

clean:
	rm -f thread1 thread2 thread3 thread3a thread4 thread5 thread6 thread6a thread7 thread7a thread8 thread8a


