
clean:
	make -C advanced_cdd clean
	make -C basics_cdd clean
	make -C blocking_io clean
	make -C concurrency clean
	make -C interrupts_linux clean
	make -C kernelmech/Kernel_Threads/KT clean
	make -C kernelmech/Kernel_Timers/Kernel_Timers clean
	make -C kernelmech/Kernel_Timers/Long_Delay/Busy_wait clean
	make -C kernelmech/Kernel_Timers/Long_Delay/Sleep_wait clean
	make -C interrupts_linux clean
